### ISSUE TITLE
Consider node_interop

### ISSUE THREAD

**Issue by pulyaevskiy** [cedx/nodejs-interop.dart#1]
Hey,

Just saw you published this on Pub. Just wondering if you considered existing node_interop package. If you did curious what was not working for you. I’m the maintainer of that package, so looking for feedback.

Make sure to check out 0.1 beta channel here:
https://pub.dartlang.org/packages/node_interop/versions/0.1.0-beta.6

**Comment by cedx** [comment]
Yes, of course I looked at your library, and also this one: [nodejs](https://pub.dartlang.org/packages/nodejs). I found them both well :)

But I simply preferred to opt for my own solution as an exercise. I wanted to both train in JS interop and bring some of my Node.js projects to Dart. I needed more complete bindings... and wanted to experiment further. I also wanted the Node.js documentation replicated in the Dartdoc one.

So nothing wrong with your library: a simple desire to create my own version / vision of this project :)
